###############################################################################
# copyright(c) 2013 Shashank
# Shared under GPL V2
###############################################################################
default: 
	g++ -I include src/Test.cpp -o gc.out
clean: 
	rm -rf src/*.o
	rm gc.out
